version: 2

project_name: shiphoist

builds:
  - main: ./cmd/shiphoist
    binary: shiphoist
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w 
      - -X github.com/potibm/shiphoist/cmd/shiphoist.Version={{.Version}}
      - -X github.com/potibm/shiphoist/cmd/shiphoist.Commit={{.Commit}}
      - -X github.com/potibm/shiphoist/cmd/shiphoist.Date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - oss-licenses/**/*

checksum:
  name_template: "checksums.txt"

release:
  mode: append
  prerelease: auto

sboms:
  - artifacts: archive