sonar.projectKey=potibm_shiphoist
sonar.organization=potibm

sonar.projectName=shiphoist

sonar.sources=.
sonar.tests=.

sonar.test.inclusions=**/*_test.go

sonar.exclusions=**/vendor/**

sonar.coverage.exclusions=cmd/**

sonar.go.coverage.reportPaths=coverage.out