name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-26.04
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      # The following steps run ONLY when the release PR has been merged:
      - name: Checkout
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          ref: ${{ steps.release.outputs.tag_name }}
          
      - name: Set up Go
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: 'go.mod'

      - name: Generate licenses
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          go install github.com/google/go-licenses@latest
          go-licenses save ./... --save_path=./oss-licenses

      - name: Install Syft for SBOMs
        if: ${{ steps.release.outputs.releases_created }}
        uses: anchore/sbom-action/download-syft@v0

      - name: Run GoReleaser
        if: ${{ steps.release.outputs.releases_created }}
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}